Name: DeviceSettingsWidget
Id: g=ee154e1badea85ef63404d0362dc266f
Type: FolderType
Children:
- Name: DeviceSettingsWidget
  Id: g=343e9a553a1648e3de95b91f6d877b43
  Supertype: Screen
  ReferenceType: HasComponent
  Children:
  - Name: HorizontalAlignment
    Id: g=b366e1988621e013a77ba2bc3af8e8f1
    Type: BaseVariableType
    DataType: HorizontalAlignment
    ModellingRule: Optional
    Value: 0
  - Name: VerticalAlignment
    Id: g=5d2cc284e65d7be8060f37bb31c39e84
    Type: BaseVariableType
    DataType: VerticalAlignment
    ModellingRule: Optional
    Value: 0
  - Name: Width
    Id: g=351b2f690c57b4088c6f3855e3472b26
    Type: BaseVariableType
    DataType: Size
    ModellingRule: Optional
    Value: 400.0
  - Name: Height
    Id: g=7d356b50e63e165f8c33e264738bd7d0
    Type: BaseVariableType
    DataType: Size
    ModellingRule: Optional
    Value: 240.0
  - Name: NavigationPanel1
    Id: g=8627dd6cafeea9ebf7c38b6511b68449
    Type: NavigationPanel
    Children:
    - Name: Panels
      Id: g=5d31f0d65168d1d10bb7b83d938d1e3f
      Type: BaseObjectType
      Children:
      - Name: Panel1
        Id: g=a445a883c0787256752b428a0ea17a90
        Type: NavigationPanelItem
        Children:
        - Name: Title
          Id: g=b6aab3d737277b661a565faf2f9aab0f
          Type: BaseDataVariableType
          DataType: LocalizedText
          Value: {"NamespaceIndex":18,"TextId":"Configuration"}
        - Name: Panel
          Id: g=e356c0cdbd6385e77d21b277bc301d66
          Type: NodePointer
          DataType: NodeId
          Value: {"IdType":2,"Id":"9cf154c923572624320f16c16fa657a3","Namespace":18}
          Children:
          - Name: Kind
            Id: g=7c21889eaba89b17b29535c72ee08620
            Type: PropertyType
            DataType: NodeId
            Value: {"Id":71,"Namespace":6}
        - Name: AliasNode
          Id: g=c573f34209e8a6405d3f71a3e4403340
          Type: BaseDataVariableType
          DataType: NodeId
          Value: {"IdType":0,"Id":0,"Namespace":-1}
          Children:
          - Name: DynamicLink
            Id: g=cb85e8e0eae2221cb3b3011074fc2aa1
            Type: DynamicLink
            DataType: NodePath
            Value: "../../../../SystemNode@NodeId"
      - Name: Panel2
        Id: g=8569aa2da03ee2d52418c9ce8b98cab1
        Type: NavigationPanelItem
        Children:
        - Name: Title
          Id: g=67fa46aac84f1285132a89295ec912ff
          Type: BaseDataVariableType
          DataType: LocalizedText
          Value: {"NamespaceIndex":18,"TextId":"ProductInformation"}
        - Name: Panel
          Id: g=74b0b47ea66ef181a073a669981acc0a
          Type: NodePointer
          DataType: NodeId
          Value: {"IdType":2,"Id":"548a589cc1532b072d9d24316f7b6090","Namespace":18}
          Children:
          - Name: Kind
            Id: g=f68b2368e310964643b23ca7ceea6772
            Type: PropertyType
            DataType: NodeId
            Value: {"Id":71,"Namespace":6}
        - Name: AliasNode
          Id: g=9db5b92cc60d0d377ebb30735f69ea56
          Type: BaseDataVariableType
          DataType: NodeId
          Value: {"IdType":0,"Id":0,"Namespace":-1}
          Children:
          - Name: DynamicLink
            Id: g=1b1e1a425e3ff7374c56095d0a1c7219
            Type: DynamicLink
            DataType: NodePath
            Value: "../../../../SystemNode@NodeId"
      - Name: Panel3
        Id: g=bfabeb41bddec14886e49e0dc510856a
        Type: NavigationPanelItem
        Children:
        - Name: Title
          Id: g=065365bb5ca3687225b72e3f5bbea879
          Type: BaseDataVariableType
          DataType: LocalizedText
          Value: {"NamespaceIndex":18,"TextId":"Diagnostics"}
        - Name: Panel
          Id: g=5bdca4af7d2533512dbb0847c98d2cd8
          Type: NodePointer
          DataType: NodeId
          Value: {"IdType":2,"Id":"632709bc0ca708c922da2f68cb20eb09","Namespace":18}
          Children:
          - Name: Kind
            Id: g=70ad51e6c8cbf2b07e816d288ea6af64
            Type: PropertyType
            DataType: NodeId
            Value: {"Id":71,"Namespace":6}
        - Name: AliasNode
          Id: g=c366c3ceb0aba9fafa194c2d7da9e3e9
          Type: BaseDataVariableType
          DataType: NodeId
          Value: {"IdType":0,"Id":0,"Namespace":-1}
          Children:
          - Name: DynamicLink
            Id: g=2c4173bd402ace68d9763155c60d69fc
            Type: DynamicLink
            DataType: NodePath
            Value: "../../../../SystemNode@NodeId"
    - Name: CurrentPanel
      Id: g=590ddc41d9c0c9acfbed8517ad5dd9e4
      Type: NodePointer
      DataType: NodeId
      AccessLevel: Read
      Value: {"IdType":0,"Id":0,"Namespace":-1}
      Children:
      - Name: Kind
        Id: g=324a5d97f114d3e06d0300651b071a40
        Type: PropertyType
        DataType: NodeId
        Value: {"Id":6,"Namespace":6}
    - Name: Width
      Id: g=9e380f90850880bc694402e1f973e6e2
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 304.0
    - Name: Height
      Id: g=a88e2ec47369901b055646310f00b51f
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 240.0
    - Name: HorizontalAlignment
      Id: g=bb168886983604db40ba7d2f3076d19a
      Type: BaseVariableType
      DataType: HorizontalAlignment
      ModellingRule: Optional
      Value: 3
    - Name: VerticalAlignment
      Id: g=67c14528330c6ca5e7281c48c08aaa92
      Type: BaseVariableType
      DataType: VerticalAlignment
      ModellingRule: Optional
      Value: 3
    - Name: TopMargin
      Id: g=6f874b6d8d85aaa3dd8e253258951b06
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 0.0
    - Name: BottomMargin
      Id: g=e9deb5a66d6c336d5119ebfb89104289
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 0.0
    - Name: CurrentTabIndex
      Id: g=a5a2e550ffd557cf7fc6073b43c8f406
      Type: BaseDataVariableType
      DataType: Int32
      Value: 0
    - Class: Reference
      Target: ns=5;i=1181
    - Class: Reference
      Target: ns=5;i=1183
  - Name: SystemNode
    Id: g=f82299aa6ce3a1b4e085c17004673eeb
    Type: NodePointer
    DataType: NodeId
    Value: {"IdType":2,"Id":"ec6e454a68ebbe1d2909d93aa145ec1b","Namespace":18}
    Children:
    - Name: Kind
      Id: g=eab78ef8cd9499846c093f97dc092aed
      Type: PropertyType
      DataType: NodeId
      Value: {"Id":1,"Namespace":16}
  - Name: DeviceSettingsWidgetLogic
    Id: g=d2b6d6687587e853572e277c487cc682
    Type: NetLogic
- File: DeviceSettingsWidgetComponents/DeviceSettingsWidgetComponents.yaml
